// This file is auto-generated by the Vercel build step.
// During local development, RAILWAY_API_URL is empty so app.js
// uses the relative /api/v1 path (served by the local FastAPI server).
window.RAILWAY_API_URL = "";
